import codes from '../../data/team-codes.json';
import {test, after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {NextRequest} from 'next/server';
const dir=mkdtempSync(join(tmpdir(),'rally-api-'));
process.env.RALLY_DATA_DIR=dir;
import {GET,POST} from '../../src/app/api/rally/route';
import {getStore} from '../../src/rally/store';
after(()=>{getStore().close();rmSync(dir,{recursive:true,force:true});});
const url='http://localhost:3000/api/rally';
function req(body:unknown, cookie?:string, origin='http://localhost:3000') { return new NextRequest(url,{method:'POST',headers:{origin,'content-type':'application/json',...(cookie?{cookie}:{})},body:JSON.stringify(body)}); }
test('API validates origin, input, session and does not expose future coordinates',async()=>{
 assert.equal((await POST(req({action:'start',code:codes[0],teamName:'Test Team',stationNumber:1},undefined,'https://other.invalid'))).status,403);
 assert.equal((await POST(req({action:'start',code:codes[0],teamName:'Test Team',stationNumber:28}))).status,400);
 assert.equal((await POST(req({action:'confirm',nonce:'a'.repeat(48),samples:[]}))).status,400);
 assert.equal((await POST(req({action:'challenge'}))).status,401);
 assert.equal((await POST(req({action:'start',code:'INVALID',teamName:'Team',stationNumber:1}))).status,400);
 assert.equal((await POST(req({action:'start',stationNumber:1}))).status,400);
 const response=await POST(req({action:'start',code:codes[0],teamName:'Test Team',stationNumber:5})); assert.equal(response.status,200);
 const cookie=response.headers.get('set-cookie')!; assert.match(cookie,/HttpOnly/i);assert.match(cookie,/SameSite=strict/i);
 const value=await response.json(); assert.equal(value.run.startNumber,5); assert.equal(value.run.startedAt,null);
 assert.ok(!JSON.stringify(value).includes('radiusMeters'));
 const session=cookie.split(';')[0];
 assert.equal((await POST(req({action:'start',code:codes[0],teamName:'Test Team',stationNumber:6},session))).status,409);
 const restored=await GET(new NextRequest(url,{headers:{cookie:session}}));assert.equal((await restored.json()).run.startNumber,5);
 const joined=await POST(req({action:'join',code:codes[0]}));assert.equal(joined.status,200);
 const peerCookie=joined.headers.get('set-cookie')!.split(';')[0];assert.notEqual(peerCookie,session);
 assert.equal((await joined.json()).run.teamName,'Test Team');
 assert.equal((await POST(req({action:'join',code:'INVALID'}))).status,400);
 const c=await (await POST(req({action:'challenge'},session))).json();assert.match(c.nonce,/^[a-f0-9]{48}$/);
 const reset=await POST(req({action:'reset'},session));assert.equal(reset.status,200);assert.match(reset.headers.get('set-cookie')!,/Max-Age=0/i);
 const peer=await GET(new NextRequest(url,{headers:{cookie:peerCookie}}));assert.equal((await peer.json()).run.startNumber,5);
 const detached=await GET(new NextRequest(url,{headers:{cookie:session}}));assert.equal((await detached.json()).run,null);
});
